version: '3'
services:
  postgresql:
    container_name: "db_postgress"
    image: postgres
    volumes:
      - "./postgres_data/postgres.conf:/usr/local/etc/postgres/postgres.conf"
      - "./postgres_data/data:/var/lib/postgresql/data:delegated"
      - "./schemas:/docker-entrypoint-initdb.d"
    command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"
    ports:
      - 5432:5432
    env_file:
      - database.env
